version: 0.1

phases:
  install:
    commands:
      - sudo apt-get -y update
      - sudo apt-get -y install nodejs
      - bundle update
  build:
    commands:
      - bundle exec rake spec
  post_build:
    commands:
      - git clone git@github.com:ryonext/rails_update_by_codebuild.git
      - cp Gemfile.lock ./rails_update_by_codebuild/Gemfile.lock
      - cd ./rails_update_by_codebuild/Gemfile.lock
      - git checkout -b bundle_update_`date "+%s"`
      - git add Gemfill.lock
      - git commit -m "Today's bundle update"
       # create PR

