version: 0.1

phases:
  install:
    commands:
      - sudo yum update
      - sudo yum -y install nodejs
      - bundle update
  build:
    commands:
      - bundle exec rake spec
  post_build:
    commands:
      - sh ./post_build.sh
